Fix In the lab video links
starteam/starcellbio_html pull request #742
Opened 2016-11-08 22:16 UTC by annagav

#### What are the relevant tickets?
Fix #24
#### What's this PR do?
Change "In the Lab" embedded videos to be link images to youtube.
Now when you click on the image a new tab opens up with the corresponding video on youtube.

2016-11-27 22:30 UTC, pdpinch commented
Looks like the thumbnail images are missing?

2016-12-05 00:57 UTC, pdpinch requested changes
I see the images, but It looks like the paths are wrong, or the images aren't in the right directories.

2016-12-05 00:57 UTC, pdpinch commented on html_app/ui/facs.soy
> +                        src="images/microscopy/videos/video_3.jpg">
Shouldn't this be in the facs directory?

2016-12-05 00:57 UTC, pdpinch commented on html_app/ui/western_blot.soy
> +                        src="images/western_blot/videos/video_1.jpg">
should this be `images/western_blot/youtube_links/video_1.jpg` ?

2016-12-05 00:57 UTC, pdpinch commented on html_app/ui/western_blot.soy
> +                        src="images/western_blot/videos/video_2.jpg">
should this be `images/western_blot/youtube_links/video_2.jpg` ?

2016-12-05 00:57 UTC, pdpinch commented on html_app/ui/western_blot.soy
> +                        src="images/western_blot/videos/video_3.jpg">
should this be `images/western_blot/youtube_links/video_3.jpg` ?

2016-12-05 00:57 UTC, pdpinch commented on html_app/ui/western_blot.soy
> +                        src="images/western_blot/videos/video_4.jpg">
should this be `images/western_blot/youtube_links/video_4.jpg` ?

2016-12-05 00:57 UTC, pdpinch commented on html_app/ui/microscopy.soy
> +                    src="images/microscopy/videos/video_3.jpg">
I think these images have the wrong path too.

2016-12-07 22:35 UTC, annagav commented on html_app/ui/facs.soy
> +                        src="images/microscopy/videos/video_3.jpg">
FACS and Microscopy have one overlapping video.

2016-12-08 15:32 UTC, annagav commented
@pdpinch I think I fixed all the links.

2016-12-08 16:41 UTC, merged