Idegtiarov/lti provider
starteam/starcellbio_html pull request #764
Opened 2017-07-20 18:25 UTC by idegtiarov

PR adds application with LTI Provider to the StarCellBio project

2017-07-25 16:18 UTC, annagav commented on StarCellBio/settings.py
> -    'django.middleware.csrf.CsrfViewMiddleware',
Why are we removing this?

2017-07-26 09:37 UTC, idegtiarov commented on StarCellBio/settings.py
> -    'django.middleware.csrf.CsrfViewMiddleware',
I've added this middleware in commit #31106d6 and found that it broke frontend tests that is why I removed it as it was in initial state.

2017-07-27 20:23 UTC, auraz requested changes

2017-07-27 20:23 UTC, auraz commented on lti_provider/lti_settings.py
> +# Uncoment to switch off LTI ssl requirements (only for development mode)
UncomMent, typo.

2017-07-27 20:23 UTC, auraz commented on lti_provider/models.py
> +            logger.debug("Start User {} logining...".format(self.scb_user.username))
Typo, logging.

2017-07-27 20:23 UTC, auraz commented on lti_provider/models.py
> +            logger.debug("Check User is authenticated:: {}".format(request.user.is_authenticated()))
Rephrase plz.

2017-07-27 20:23 UTC, auraz commented on lti_provider/unit_tests/test_views.py
> +    m = Mock()
single value names are restricted by pep8, i suppose.

2017-07-27 20:23 UTC, auraz commented on lti_provider/validator.py
> +        return True
Where is noonce validated here?

2017-07-27 20:23 UTC, auraz commented on lti_provider/validator.py
> +        logger.debug('Client key is validating...')
Please rephrase to be stateful.

2017-07-27 20:23 UTC, auraz commented on lti_provider/views.py
> +    # FIXME(idegtiarov) there is no extentions right now, if they don't appear remove example.
Please clarify this during pull request review, or change comment text.

2017-07-27 20:23 UTC, auraz commented on lti_provider/views.py
> +        # TODO(idegtiarov) add lti_error page if it is needed
Clean or fix TODO plz.

2017-07-27 20:23 UTC, auraz commented on lti_provider/views.py
> +        # TODO(idegtiarov) add lti_error page if it is needed
Clean or fix TODO plz.

2017-07-27 20:23 UTC, auraz commented on lti_provider/views.py
> +        # TODO(idegtiarov) add lti_error page if it is needed
Clean or fix TODO plz.

2017-07-27 20:23 UTC, auraz commented on lti_provider/views.py
> +            # TODO(idegtiarov) add lti_error page if it is needed
Clean or fix TODO plz.

2017-07-28 08:53 UTC, idegtiarov commented on lti_provider/lti_settings.py
> +# Uncoment to switch off LTI ssl requirements (only for development mode)
done

2017-07-28 08:53 UTC, idegtiarov commented on lti_provider/models.py
> +            logger.debug("Start User {} logining...".format(self.scb_user.username))
fixed

2017-07-28 08:57 UTC, idegtiarov commented on lti_provider/validator.py
> +        return True
We inherit oauth1.RequestValidator functions and timestamp is validated with `validate_timestamp_and_nonce` function. Nonce is not validating here.

2017-07-28 08:59 UTC, idegtiarov commented on lti_provider/validator.py
> +        logger.debug('Client key is validating...')
done

2017-07-28 09:00 UTC, idegtiarov commented on lti_provider/views.py
> +    # FIXME(idegtiarov) there is no extentions right now, if they don't appear remove example.
We are not interested in any extension parameters, I remove this comment

2017-07-28 09:11 UTC, idegtiarov commented on lti_provider/views.py
> +        # TODO(idegtiarov) add lti_error page if it is needed
Done

2017-07-28 09:11 UTC, idegtiarov commented on lti_provider/views.py
> +        # TODO(idegtiarov) add lti_error page if it is needed
done

2017-07-28 09:12 UTC, idegtiarov commented on lti_provider/views.py
> +        # TODO(idegtiarov) add lti_error page if it is needed
done

2017-07-28 09:12 UTC, idegtiarov commented on lti_provider/views.py
> +            # TODO(idegtiarov) add lti_error page if it is needed
done

2017-07-28 09:19 UTC, auraz requested changes

2017-07-28 09:19 UTC, auraz commented on lti_provider/views.py
> +    except oauth1.OAuth1Error as err:
Can this error be raised here too DjangoToolProvider.from_django_request(request=request) ?

2017-07-28 09:19 UTC, auraz commented on lti_provider/views.py
> +        logger.debug('Check user was created {}'.format(user.is_scb_user))
please rephrase, what do you mean here?

2017-07-28 09:20 UTC, auraz requested changes

2017-07-28 09:20 UTC, auraz commented on lti_provider/validator.py
> +        return True
why it is passed and mentioned in name?

2017-07-28 09:40 UTC, idegtiarov commented on lti_provider/views.py
> +    except oauth1.OAuth1Error as err:
Here can be raised two other errors InvalidLTIRequestError abd ValueError. Add them in except checking block.

2017-07-28 09:43 UTC, idegtiarov commented on lti_provider/views.py
> +        logger.debug('Check user was created {}'.format(user.is_scb_user))
done

2017-07-28 09:51 UTC, idegtiarov commented on lti_provider/unit_tests/test_views.py
> +    m = Mock()
Not allowed to use only: l, O, and I variables.

2017-07-28 09:53 UTC, idegtiarov commented on lti_provider/validator.py
> +        return True
Because in Oauth1 authentication this two params used and validated in pairs.

2017-07-28 14:54 UTC, annagav commented
@idegtiarov, While deploying to our qa site there were at least a couple of dependencies missing in requirements.txt. Could you please update it?

2017-07-28 15:14 UTC, idegtiarov commented
@annagav Yes sure I will check.

2017-07-31 10:00 UTC, idegtiarov commented
@annagav I merge latest develop branch and run SCB in the new vagrant instance, requirements.txt covers all dependencies. If you know what packages should be added or updated please let me know.

2017-07-31 14:03 UTC, annagav commented
Functionality works great! 👍

2017-07-31 14:04 UTC, annagav approved these changes

2017-07-31 15:29 UTC, merged