Fix LTI validation process
starteam/starcellbio_html pull request #767
Opened 2017-08-01 21:39 UTC by idegtiarov

It was found out that LTI validation process has mixes of checking and validating methods.

This PR clarify LTI validation process and remove redundant methods.

All client_key validation process is moved to `validate_client_key` method. 
Method `check_client_key` was removed as redundant one.

In `validate_timestamp_and_nonce` is added timestamp checking that cannot be less than previous request's timestamp received from the certain LTI consumer. And nonce checking that cannot be duplicated. 

Timestamp and nonce are storing in the cache with the TIMEOUT option which is by default set to 10 seconds and it is fair enough to prevent replay-attack through the LTI.

Add README file with the link to documentation.

2017-08-02 08:49 UTC, auraz requested changes

2017-08-02 08:49 UTC, auraz commented on StarCellBio/settings.py
> +    'lti_cache': {
Why use different cache and not the same?

2017-08-02 08:49 UTC, auraz commented on lti_provider/validator.py
> +        cache_timestamp = self.cache.get(timestamp_key, timestamp)
i do not think we need to cache timestamp, we can just check that current time is within 10 seconds from timestamp. Can discuss it.

2017-08-02 11:21 UTC, idegtiarov commented on lti_provider/validator.py
> +        cache_timestamp = self.cache.get(timestamp_key, timestamp)
Timestamp is already checked that it is within `timestamp_lifetime` from the current time in `oauthlib.oauth1.rfc5849.endpoints.base` L167. Here we validate timestamp where validation is: 
```
The timestamp value MUST be a positive integer and MUST be equal or greater than the timestamp used in previous requests.
```
Taken from the documentation [link](https://oauth.net/core/1.0/#nonce)

2017-08-02 11:43 UTC, idegtiarov commented on StarCellBio/settings.py
> +    'lti_cache': {
We add pretty small TIMEOUT param which makes the cache to delete overdue data.

2017-08-02 14:26 UTC, auraz approved these changes

2017-08-02 14:26 UTC, auraz commented on StarCellBio/settings.py
> +    'lti_cache': {
please add comment

2017-08-02 14:26 UTC, auraz commented on lti_provider/validator.py
> +        cache_timestamp = self.cache.get(timestamp_key, timestamp)
thank you

2017-08-03 12:53 UTC, auraz approved these changes

2017-08-03 12:53 UTC, auraz commented on lti_provider/validator.py
> +        Validate LTI request's timestamp and nonce
update docstring

2017-08-03 13:48 UTC, idegtiarov commented on StarCellBio/settings.py
> +    'lti_cache': {
done

2017-08-03 14:13 UTC, idegtiarov commented on lti_provider/validator.py
> +        Validate LTI request's timestamp and nonce
done

2017-08-03 14:41 UTC, annagav commented
Looks good 👍

2017-08-03 14:46 UTC, merged