Improve histograms
starteam/starcellbio_html pull request #778
Opened 2017-11-20 11:20 UTC by jmclaus

- Add upper value for y-axis and implement log scale.
- Remove x-axis ticks field. Ticks for both axis will be automatically generated.
- Remove former preview canvases. Use square canvases to match student view.
- Use polyline with draggable points to set up a guide for the noisy curve whose variation is determined by a slider
- Use 'pointer' cursor for histogram tabs.

2017-11-20 18:33 UTC, annagav requested changes

2017-11-20 18:33 UTC, annagav commented on instructor/migrations/0023_flowcytometry.py
>                              )
Why this is not a new migration to modify the fields of an existing model? Are we supposed to unapply `0023_flowcytometry`?

2017-11-21 11:02 UTC, jmclaus commented on instructor/migrations/0023_flowcytometry.py
>                              )
@annagav Good catch, thank you. It is corrected, reverted the changes to the above file and instead created a new migration called `0034_improve_histograms.py`

2017-11-21 11:03 UTC, jmclaus commented
@annagav @idegtiarov I rebased the branch on develop and checked out that it didn't break anything with @idegtiarov recent merge.

2017-11-21 19:51 UTC, annagav commented
Works great! The only thing the button doesn't fit the dialog:
![screen shot 2017-11-21 at 2 47 03 pm](https://user-images.githubusercontent.com/7574259/33093624-72d615d2-cecb-11e7-84cb-53ae4dff5052.png)

2017-11-22 10:56 UTC, jmclaus commented
@annagav Thanks. I fixed the button positioning and also decreased a bit the size of the div containing the histogram library so that only exactly 2 rows appear. I have scrollbars on both latest Chromium and Firefox but I do not see any in your screenshot. Do you have any?

![select-histogram-popup](https://user-images.githubusercontent.com/1427382/33124009-10319f26-cf7c-11e7-8d36-f0073aca03ff.png)

2017-11-22 20:45 UTC, annagav approved these changes

2017-11-22 20:47 UTC, annagav commented
@jmclaus On a Mac the scroll bars are only visible when you are scrolling. I don't think this is a problem. 
Looks good! 👍

2017-11-22 20:51 UTC, jmclaus commented
@annagav OK, great, I am on Linux. Will merge this when I get final approval from @laleman.

2017-11-22 23:01 UTC, merged